# Generated by Django 4.0.5 on 2022-06-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0004_alter_tag_description_alter_tag_priority'),
        ('category', '0009_alter_category_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_categories', to='category.category')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_tags', to='tag.tag')),
            ],
            options={
                'db_table': 'category_tag',
                'ordering': ('tag', 'category'),
                'managed': True,
                'unique_together': {('tag', 'category')},
            },
        ),
    ]
