# Generated by Django 3.2.3 on 2021-05-21 02:55

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('email', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('DENTIST', 'DENTIST'), ('LAB', 'LAB'), ('ORTHODONTIST', 'ORTHODONTIST')], max_length=15)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('mal', 'mal'), ('formal', 'formal')], max_length=10)),
                ('telnumber', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('confirmed', models.BooleanField(default=False)),
                ('plat_form', models.CharField(blank=True, choices=[('WEB', 'WEB'), ('IPHONE', 'IPHONE'), ('ANDROID', 'ANDROID')], default='WEB', max_length=10)),
                ('udid', models.CharField(blank=True, max_length=64, null=True)),
                ('banned', models.BooleanField(blank=True, default=False)),
                ('banned_date', models.DateTimeField(blank=True, null=True)),
                ('new_email', models.CharField(blank=True, max_length=60, null=True)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member',
                'ordering': ('-id',),
                'managed': True,
                'unique_together': {('email', 'type')},
            },
        ),
    ]
