# Generated by Django 3.2.3 on 2021-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active_notification',
            field=models.BooleanField(default=True),
        ),
    ]
