# Generated by Django 3.2.3 on 2021-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='player_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
