# Generated by Django 3.2.3 on 2022-03-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='permanent_discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
