# Generated by Django 3.2.3 on 2022-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_member_permanent_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=15),
        ),
    ]
