# Generated by Django 4.0.5 on 2022-06-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20220609_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='telnumber',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
