# Generated by Django 4.0.5 on 2022-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_member_birth_date_alter_member_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
