# Generated by Django 4.0.5 on 2022-06-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='floor',
            field=models.DecimalField(blank=True, decimal_places=18, default=0.0, max_digits=50, null=True),
        ),
    ]
