# Generated by Django 4.0.5 on 2022-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='files',
            field=models.JSONField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
