# Generated by Django 4.0.5 on 2022-06-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True, 'ordering': ('priority',)},
        ),
    ]
