# Generated by Django 4.0.5 on 2022-06-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
