# Generated by Django 4.0.5 on 2022-06-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ethereum', '0007_ethereum_views'),
        ('member', '0010_alter_member_birth_date_alter_member_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ethereum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethereum_favorits', to='ethereum.ethereum')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_favorits', to='member.member')),
            ],
            options={
                'db_table': 'favorit',
                'ordering': ('member', 'ethereum'),
                'managed': True,
                'unique_together': {('member', 'ethereum')},
            },
        ),
    ]
