# Generated by Django 4.0.5 on 2022-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0003_ethereum_address_ethereum_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethereum',
            name='owners',
        ),
        migrations.AddField(
            model_name='ethereum',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
