# Generated by Django 4.0.5 on 2022-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0004_remove_ethereum_owners_ethereum_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereum',
            name='registrant',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ethereum',
            name='resolver',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
