# Generated by Django 4.0.5 on 2022-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0006_ethereum_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereum',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
