# Generated by Django 4.0.5 on 2022-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0007_ethereum_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereum',
            name='owners',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
